version: '3.3'
services:
  api:
    build: .
    command: npm run start:script
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 8000:8000
    depends_on:
      - postgres
    links:
      - postgres
    environment:
      NODE_ENV: $NODE_ENV
      DATABASE_URL: $DATABASE_URL

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: $POSTGRES_DB
    ports:
      - 5434:5432
